### ISSUE TITLE
v2, todo

### ISSUE THREAD

**Issue by larshp** [abap-openapi/abap-openapi#67]
- [ ] 	allow prefixing the path via generation
- [ ] 	add test case with multiple operations, server
- [ ] 	parameters in paths
